### ISSUE TITLE
Компонент "нам доверяют"

### ISSUE THREAD

**Issue by frylock34** [stereotech/stereotech.org#110]
Добавить компонент на главную страницу "Нам доверяют"

По виду карточка. по середине заголовок, под ним логотипы компаний (пример на изображении)

![image](https://user-images.githubusercontent.com/16722747/119306951-9c089080-bc73-11eb-830e-baa47f075736.png)

компонент расположить под основным баннером

**Comment by frylock34** [comment]
[logos.zip](https://github.com/stereotech/stereotech.org/files/6530361/logos.zip)

Логотипы (изменить размер до необходимого)
логотип ВНМ к сожалению очень плохой

**Comment by Kate8954** [comment]
возможно стоит сделать логотипы поменьше
