### ISSUE TITLE
Добавить страницу "Пресс-центр" в раздел инфо

### ISSUE THREAD

**Issue by Avdartrom** [stereotech/stereotech.org#121]
Организовать страницу на подобии https://fasie.ru/press/
Добавить ссылку на медиа ресурсы: https://drive.google.com/drive/folders/11fw6TStFLdtxZ66Oxrg4xrI7gCEs7wBd?usp=sharing
Добавить ссылку на плейлист ютуб: https://youtube.com/playlist?list=PLpJTPL5twL-4bOAtLpnqyBxoCi0NR9UdG
Добавить ссылку на презентацию: https://drive.google.com/file/d/1haJ7X9HS3XwRbQVP-sj_3rRZIoJEdT3m/view?usp=sharing
Добавить ссылку на брендбук (без доступа в соседние разделы): https://work-documentation-stereotech.stereotech.org/brandbook/

Оставить контакты Вероники, как КОНТАКТЫ ДЛЯ ПРЕССЫ:

**Comment by frylock34** [comment]
Презентацию можно встроить, например вот так
![image](https://user-images.githubusercontent.com/16722747/142979925-ff46371b-b1c7-466a-a72c-353c8d7746f9.png)

**Comment by Avdartrom** [comment]
А она сможет подхватить ее с гугл ссылки? Там мы ее обновляем периодически
