### ISSUE TITLE
В разделы и подразделы "Материалы для печати" добавить "памятку выбора материала"

### ISSUE THREAD

**Issue by Avdartrom** [stereotech/stereotech.org#122]
На страницы с раздела https://stereotech.org/materials и ниже, последним блоком разместить памятку https://drive.google.com/file/d/1AGuLPv2NiyIoa84Bj0cW8GtGc1YOFUE5/view?usp=sharing

Блок схема в формате Visio есть на сервере, если понадобится.Z:\Продукция Stereotech\Производство материалов для печати

**Comment by Avdartrom** [comment]
Так же добавить ссылку на все брошюры с материалами https://drive.google.com/drive/folders/1AIMZhAqIwwiQwO4HExZw3kOIoBO1GaNR?usp=sharing

**Comment by frylock34** [comment]
@Avdartrom 
![image](https://user-images.githubusercontent.com/16722747/144204174-53c201ee-6b77-4901-96e5-31a3d4f8cf3e.png)
![image](https://user-images.githubusercontent.com/16722747/144204185-99f8d10f-31a5-4964-9921-04094eea0c26.png)

**Comment by frylock34** [comment]
closed via https://github.com/stereotech/stereotech.org/commit/f673201330636b6bbf7e22f49c1da3726c2c0e86
