### ISSUE TITLE
Обновить блок характеристик моделей

### ISSUE THREAD

**Issue by Avdartrom** [stereotech/stereotech.org#54]
Характеристики брать отсюда:
D:\Продвижение Stereotech\Материалы для дилеров\Информация по Оборудованию.xlsx

Блок выстроить в виде одной таблицы с характеристиками всех моделей в серии для удобства их сравнения.

**Comment by frylock34** [comment]
связяно с #28

**Comment by frylock34** [comment]
Оформить все в Cockpit
